# Generated by Django 5.2.12 on 2026-07-06 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
        ('products', '0002_remove_product_latitude_remove_product_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barterrequest',
            name='extra_offer',
        ),
        migrations.RemoveField(
            model_name='barterrequest',
            name='requested_product',
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='msg',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='request_for_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_requested', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='request_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_offered', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replaceoption',
            name='icon',
            field=models.CharField(default='noto:package', max_length=100),
        ),
        migrations.AddField(
            model_name='replaceoption',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaceoption',
            name='point_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaceoption',
            name='replace_type',
            field=models.CharField(blank=True, default='product', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='barterrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='replaceoption',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='replaceoption',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='replaceoption',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SaveProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
