# Generated by Django 6.0.1 on 2026-01-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0001_initial"),
        ("products", "0005_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="replaceoption",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replaceoption",
            name="point_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replaceoption",
            name="replace_type",
            field=models.CharField(
                choices=[("product", "Product"), ("point", "Point")],
                default="product",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="replaceoption",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="replaceoption",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
