# Generated by Django 6.0.1 on 2026-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_replaceoption_meta_replaceoption_point_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaceoption',
            name='replace_type',
            field=models.CharField(default='product', max_length=10),
        ),
    ]
