# Generated by Django 6.0.1 on 2026-02-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_alter_replaceoption_replace_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaceoption',
            name='replace_type',
            field=models.CharField(blank=True, default='product', max_length=10, null=True),
        ),
    ]
