# Generated by Django 6.0.1 on 2026-03-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0004_alter_replaceoption_replace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaceoption',
            name='icon',
            field=models.CharField(default='noto:package', max_length=100),
        ),
    ]
