# Generated by Django 6.0.1 on 2026-03-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0005_replaceoption_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barterrequest',
            name='extra_offer',
        ),
    ]
