# Generated by Django 6.0.1 on 2026-03-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0006_remove_barterrequest_extra_offer'),
        ('products', '0014_remove_product_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barterrequest',
            name='requested_product',
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='request_for_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_requested', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='request_product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_offered', to='products.product'),
            preserve_default=False,
        ),
    ]
