# Generated by Django 6.0.1 on 2026-03-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0007_remove_barterrequest_requested_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterrequest',
            name='msg',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
