# Generated by Django 5.2.12 on 2026-04-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0010_saveproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replaceoption',
            name='point_value',
        ),
        migrations.RemoveField(
            model_name='replaceoption',
            name='replace_type',
        ),
    ]
