# Generated by Django 5.2.12 on 2026-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0011_remove_replaceoption_point_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replaceoption',
            name='point_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replaceoption',
            name='replace_type',
            field=models.CharField(blank=True, default='product', max_length=10, null=True),
        ),
    ]
