# chat/consumers.py

import json
import logging
from channels.generic.websocket import AsyncWebsocketConsumer
from channels.db import database_sync_to_async
from django.contrib.auth import get_user_model

User = get_user_model()
logger = logging.getLogger(__name__)


class ChatConsumer(AsyncWebsocketConsumer):

    # ─── Lifecycle ────────────────────────────────────────────────────────────

    async def connect(self):
        self.request_id   = self.scope["url_route"]["kwargs"]["request_id"]
        self.room_group   = f"chat_{self.request_id}"
        user              = self.scope.get("user")

        if not user or not user.is_authenticated:
            await self.close()
            return

        self.user         = user
        self.user_email   = user.email
        self.channel_name_saved = self.channel_name   # stable ref for pending_key

        await self.channel_layer.group_add(self.room_group, self.channel_name)
        await self.accept()

        # 1. Announce we are online to everyone else in the room
        await self.channel_layer.group_send(self.room_group, {
            "type":   "presence",
            "status": "online",
            "email":  self.user_email,
        })

        # 2. Ask everyone else in the room to tell US their status.
        #    They will respond with a targeted presence_reply back only to us.
        await self.channel_layer.group_send(self.room_group, {
            "type":           "presence_query",
            "requester_email": self.user_email,
            "reply_channel":   self.channel_name,
        })

        # 3. Send history
        messages = await self.get_history()
        await self.send(text_data=json.dumps({"type": "history", "messages": messages}))

        # 4. Mark all unread messages (sent by the OTHER user) as seen
        await self.mark_all_seen()
        await self.channel_layer.group_send(self.room_group, {
            "type":       "all_seen",
            "reader":     self.user_email,
            "request_id": self.request_id,
        })

    async def disconnect(self, code):
        if not hasattr(self, "room_group"):
            return
        await self.channel_layer.group_send(self.room_group, {
            "type":   "presence",
            "status": "offline",
            "email":  self.user_email,
        })
        await self.channel_layer.group_discard(self.room_group, self.channel_name)

    # ─── Receive from browser ─────────────────────────────────────────────────

    async def receive(self, text_data):
        data     = json.loads(text_data)
        msg_type = data.get("type", "message")

        if msg_type == "seen" and "message_id" in data:
            await self.mark_seen(data["message_id"])
            await self.channel_layer.group_send(self.room_group, {
                "type":       "seen_ack",
                "message_id": str(data["message_id"]),
                "reader":     self.user_email,
            })
            return

        text = data.get("text", "").strip()
        if not text:
            return

        # pending_key is generated by the frontend to match optimistic → confirmed
        pending_key = data.get("pending_key")

        msg = await self.save_message(self.user, text)

        await self.channel_layer.group_send(self.room_group, {
            "type":           "chat_message",
            "id":             msg["id"],
            "text":           msg["text"],
            "sender_email":   msg["sender_email"],
            "created_at":     msg["created_at"],
            "seen":           False,
            "pending_key":    pending_key,           # echoed back only to sender
            "sender_channel": self.channel_name,     # used to identify sender
        })

    # ─── Group event handlers ─────────────────────────────────────────────────

    async def chat_message(self, event):
        is_sender   = event.get("sender_channel") == self.channel_name
        pending_key = event.get("pending_key") if is_sender else None

        payload = {
            "type":         "message",
            "id":           event["id"],
            "text":         event["text"],
            "sender_email": event["sender_email"],
            "created_at":   event["created_at"],
            "seen":         event.get("seen", False),
        }
        if pending_key is not None:
            payload["pending_key"] = pending_key

        await self.send(text_data=json.dumps(payload))

    async def presence(self, event):
        # Don't echo back to the person who sent it
        if event["email"] == self.user_email:
            return
        await self.send(text_data=json.dumps({
            "type":   "presence",
            "status": event["status"],
            "email":  event["email"],
        }))

    async def presence_query(self, event):
        # Someone just connected and wants to know who's online.
        # Reply directly to their channel (not the whole group).
        if event["requester_email"] == self.user_email:
            return   # don't reply to yourself
        await self.channel_layer.send(event["reply_channel"], {
            "type":   "presence_reply",
            "status": "online",
            "email":  self.user_email,
        })

    async def presence_reply(self, event):
        # Direct message back to us — tell the frontend this user is online
        await self.send(text_data=json.dumps({
            "type":   "presence",
            "status": event["status"],
            "email":  event["email"],
        }))

    async def seen_ack(self, event):
        if event["reader"] == self.user_email:
            return
        await self.send(text_data=json.dumps({
            "type":       "seen_ack",
            "message_id": event["message_id"],
            "reader":     event["reader"],
        }))

    async def all_seen(self, event):
        if event["reader"] == self.user_email:
            return
        await self.send(text_data=json.dumps({
            "type":   "all_seen",
            "reader": event["reader"],
        }))

    # ─── DB helpers ───────────────────────────────────────────────────────────

    @database_sync_to_async
    def save_message(self, user, text):
        from .serializers import ChatMessageSerializer
        from .models import ChatMessage
        msg = ChatMessage.objects.create(
            barter_request_id=self.request_id,
            sender=user,
            text=text,
        )
        return ChatMessageSerializer(msg).data

    @database_sync_to_async
    def get_history(self):
        from .serializers import ChatMessageSerializer
        from .models import ChatMessage
        msgs = (
            ChatMessage.objects
            .filter(barter_request_id=self.request_id)
            .select_related("sender")
            .order_by("created_at")[:50]
        )
        return ChatMessageSerializer(msgs, many=True).data

    @database_sync_to_async
    def mark_seen(self, message_id):
        from .models import ChatMessage
        ChatMessage.objects.filter(
            id=message_id,
            barter_request_id=self.request_id,
        ).exclude(sender=self.user).update(seen=True)

    @database_sync_to_async
    def mark_all_seen(self):
        from .models import ChatMessage
        ChatMessage.objects.filter(
            barter_request_id=self.request_id,
            seen=False,
        ).exclude(sender=self.user).update(seen=True)