# Generated by Django 6.0.1 on 2026-01-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(default=None, upload_to="products/thumbnail"),
            preserve_default=False,
        ),
    ]
