# Generated by Django 6.0.1 on 2026-01-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="product",
            name="longitude",
        ),
    ]
