# Generated by Django 6.0.1 on 2026-01-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_latitude_remove_product_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(upload_to="thumbnails"),
        ),
    ]
