# Generated by Django 6.0.1 on 2026-02-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purches_bill',
            field=models.ImageField(blank=True, null=True, upload_to='product_bill'),
        ),
        migrations.AddField(
            model_name='product',
            name='purches_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
