# Generated by Django 6.0.1 on 2026-02-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_purches_bill_product_purches_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purches_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed')], default='Submitted', max_length=10),
        ),
    ]
