# Generated by Django 6.0.1 on 2026-02-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_purches_year_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purches_bill',
            new_name='purchase_bill',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='purches_year',
            new_name='purchase_year',
        ),
    ]
