# Generated by Django 6.0.1 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_purches_bill_product_purchase_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
