# Generated by Django 6.0.1 on 2026-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_bill',
            field=models.FileField(blank=True, null=True, upload_to='product_bill/'),
        ),
    ]
