# Generated by Django 6.0.1 on 2026-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_purchase_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='noto:package', max_length=100),
        ),
    ]
