# Generated by Django 6.0.1 on 2026-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('banned', 'Banned')], default='Submitted', max_length=10),
        ),
    ]
