# Generated by Django 5.2.12 on 2026-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('Brand New', 'Brand New'), ('Line New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('banned', 'Banned')], default='submitted', max_length=10),
        ),
    ]
