# Generated by Django 5.2.12 on 2026-05-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_bookmarkproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkproduct',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
