# Generated by Django 5.2.12 on 2026-05-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_bookmarkproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
